tunnel: fc42218d-2fb5-4720-8dbe-594228b4acda
credentials-file: /home/ubuntu/.cloudflared/twinpilot-live.json

ingress:
  - hostname: twinpilot.webyaar.in
    service: http://127.0.0.1:8080
    originRequest:
      noTLSVerify: true
      disableChunkedEncoding: true
  - service: http_status:404
